[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = "0.19.0"
neural-network = { path = "../libs/neural-network" }
genetic-algorithm = { path = "../libs/genetic-algorithm" }
nalgebra = { version = "0.33.1", features = ["rand-no-std"] }
rand = "0.8.5"
approx = "0.5.1"
